version: '3.8'

services:
  recipe-generation:
    build: .
    container_name: recipe-generation
    ports:
      - "8000:8000"
    volumes:
      - ./models:/app/models
      - ./main.py:/app/main.py
      - ./accuracy:/app/accuracy
    restart: unless-stopped
